export const GET_TASKS = 'GET_TASKS'
export const ADD_TASK = 'ADD_TASK'
export const DELETE_TASK = 'DELETE_TASK'
export const UPDATE_TASKS = 'UPDATE_TASKS'
export const COMPLETE_TASK = 'COMPLETE_TASK'
export const SELECT_TASK = 'SELECT_TASK'
